#ARDUINO_SKETCHBOOK  = /home/topisani/Arduino
BOARD_TAG = leonardo
AVRDUDE_OPTS = -V -q -F
#BOARD_SUB = 16MHzatmega32U4
MONITOR_PORT = /dev/ttyACM0
#ALTERNATE_CORE      = sparkfun
include /usr/share/arduino/Arduino.mk

# vim: ft=makefile
